### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by emoon** [kitech/qt.rs#6]
Hi,

I'm looking into using Qt5 (with Rust) for a fairly large project and I would like to know the current status of qt.rs as there hasn't been any updates for a while.

**Comment by kitech** [comment]
this project is alpha/experimental state now, and stall for a while.
much work to do.
can not use in product.
thanks.

**Comment by emoon** [comment]
Hi, Thanks for the reply. I have another question. How was the code here https://github.com/kitech/qt.inline generated?

**Comment by kitech** [comment]
Yes,  see https://github.com/kitech/qt.gen.
qt.inline and qt.rs are all generated by qt.gen.

**Comment by emoon** [comment]
Thanks!
